### ISSUE TITLE
Example Not Working

### ISSUE THREAD

**Issue by nickbuddendotcom** [hughsk/vinyl-source-stream#1]
Hi, thanks for the plugin! When I run the provided example of 

``` javascript
gulp.task('browserify', function() {
  var bundleStream = browserify('index.js').bundle()

  bundleStream
    .pipe(source('index.js'))
    .pipe(uglify())
    .pipe(gulp.dest('./bundle.js'))
})
```

I get the error `[gulp] Error in plugin 'gulp-uglify': Streaming not supported`. Am I doing something wrong?

**Comment by EvanCarroll** [comment]
Is there a way to use uglify that does this for you? Or does everyone wanting ulglify and gulp use this streamify/uglify hybrid?

**Comment by pluma** [comment]
FWIW, I replaced Gulp with a few simple package.json scripts in most of my projects, which solves this problem. You could look at [minifyify](https://www.npmjs.com/package/minifyify), though, which is basically uglify as a browserify transform.

**Comment by mwerumuchai** [comment]
$ npm install vinyl-source-stream
npm WARN pingpong@1.0.0 No repository field.

+ vinyl-source-stream@1.1.0
updated 1 package in 4.04s
  
Keeps bringing this error when I want to install vinyl-source-stream

**Comment by soundasleep** [comment]
Thank you for the workaround @ivanistheone! It works beautifully, trying to get watch/browserify to work nicely with uglify and sourcemaps.

```js
gulp.task('watch-coffee', function() {
  var watchBrowserify = watchify(browserifyInstance('./assets/javascripts/application.coffee', _.assign(watchify.args, { debug: true })));

  var updateOnChange = function() {
    return watchBrowserify
      .bundle()
      .on('error', util.log.bind(util, '\007 Browserify Error'))
      .pipe(source('bundle.js'))
      .pipe(rename(function(path) {
        path.basename += "-" + gitRevision;
      }))
      .pipe(gulp.dest('public/assets'))
      .pipe(streamify(sourcemaps.init({ loadMaps: true }))) // to persist the maps through the compression step
      .pipe(streamify(uglify({ output: { semicolons: false } })))
      .pipe(streamify(sourcemaps.write('./maps')))
      .pipe(gulp.dest('public/dist'))
      .pipe(browserSync.reload({stream:true}))
  };

  watchBrowserify
    .transform('coffeeify')
    .on('log', util.log)
    .on('update', updateOnChange);
  updateOnChange();
});
```
