### ISSUE TITLE
Dependencies in package.json are lagging in version

### ISSUE THREAD

**Issue by denver-HJS** [hughsk/vinyl-source-stream#18]
Just curious if anyone has tested the project out using the latest versions of through2 and vinyl.

Currently for this project they are set at:

```
"dependencies": {
    "vinyl": "^0.4.3",
    "through2": "^0.6.1"
  }
```

but vinyl is at 1.1.1 and through2 is all the way up to 2.0.1

I want to shrinkwrap my modules, but right now the latest of these are incompatible. It seems like it's worth investigating, but it's just my suggestion.

**Comment by phated** [comment]
Bumping these shortly - ref #24
