### ISSUE TITLE
DeprecationWarning in Node v7

### ISSUE THREAD

**Issue by JesusMurF** [hughsk/vinyl-source-stream#22]
I'm have upgrade to Node v7 and now when I use vinyl-source-stream with browserify and babelify I recive this warning on my terminal at execute gulp.

> (node:27731) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

Here my code

`gulp.task('scripts', () => {
  browserify('./src/index.js')
    .transform(babel)
    .bundle()
    .pipe(source('index.js'))
    .pipe(rename('app.js'))
    .pipe(gulp.dest('public/js'))
})`

Any solution? Thanks.

**Comment by phated** [comment]
Not used in this module.
