### ISSUE TITLE
v2.0.0 didn't work with babelify

### ISSUE THREAD

**Issue by hideo666nabe** [hughsk/vinyl-source-stream#26]
I got this error after update v2.0.0 from v1.1.0 with browserify + babelify
```
  const bundler = browserify('src/js/main.js', { transform: [babelify] });
  const bundle = () => {
    return bundler.bundle()
      .pipe(source('main.js'))
      .pipe(buffer())
...
```

```
[01:32:32] Starting 'build:javascript'...
~/node_modules/cloneable-readable/index.js:38
    throw new Error('already started')
    ^
```
and when removing babelfiy it worked.
after all, I returned v1.1.0.

is there someone with the same error?
```
my package
node v8.9.3
gulp v3.9.1
browserify 14.5.0
babelify v8.0.0
and babel-preset etc
```

**Comment by andrejewski** [comment]
I am using Babelify and have the same error in [Himalaya](https://github.com/andrejewski/himalaya/pull/78). See [Travis build](https://travis-ci.org/andrejewski/himalaya/jobs/320557742#L475) and [Gulpfile](https://github.com/andrejewski/himalaya/blob/dcb535cd7ec924d0b43aca41965910086fc2203e/gulpfile.babel.js). It would be useful to see an overview of what has changed in 2.0.0.

**Comment by phated** [comment]
Update vinyl-buffer. I had to publish a patch to fix a mistake in it

**Comment by hideo666nabe** [comment]
v2.0.0 worked with babelify after update vinyl-buffer v1.0.1. 
thanks phated!
