### ISSUE TITLE
vinyl-source-stream@1.1.1 bug 'Error: already started'

### ISSUE THREAD

**Issue by garrettbates** [hughsk/vinyl-source-stream#27]
**Context**

My project has gulp builds leveraging vinyl-source-stream that started failing with vinyl-source-stream@1.1.1 release, but work with vinyl-source-stream@1.1.0.

npm -- 5.3.0
node -- v8.4.0

**Error**

/cloneable-readable/index.js:38
    throw new Error('already started')
    ^

Error: already started
    at Cloneable.clone (/cloneable-readable/index.js:38:11)
    at File.clone (/vinyl-source-stream/node_modules/vinyl/index.js:117:30)
    at BufferList._callback (/vinyl-buffer/index.js:18:19)
    at BufferList.end (/bl/bl.js:83:10)
    at Cloneable.onend (/readable-stream/lib/_stream_readable.js:570:10)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at Cloneable.emit (events.js:207:7)
    at endReadableNT (/readable-stream/lib/_stream_readable.js:992:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)

**Pseudo code:**

```
var gulp = require('gulp');
var globalShim = require('browserify-global-shim').configure({..})
var source = require('vinyl-source-stream');
var buffer = require('vinyl-buffer');
var mergeStream = require('merge-stream');
var minifyStream = require("gulp/minify-stream");
var clone = require('gulp-clone');

gulp.task('build', function() {
   for (...) {
      var stream = browserify({entries[widgetEntryPoint]}).transform(globalShim).bundle().pipe(source('out.js')).pipe(buffer());

      minifyStream = stream.pipe(clone()).pipe(rename(function(path) {path.extname = ".min.js"}))
      .pipe(buffer())
      ...

       mergeStream(stream, minifyStream)
      .pipe(...)
   }
})

```

**Comment by phated** [comment]
I've already published a 1.1.2 version that reverts the change. However, you should upgrade to 2.0.0 and vinyl-buffer 1.0.1 so you can have proper gulp 4 support.

**Comment by fishcharlie** [comment]
@phated I'm getting this error after upgrading to 2.0

**Comment by phated** [comment]
Did you actually read the comment? You *must* update vinyl-buffer.....

**Comment by fishcharlie** [comment]
@phated Pretty sure having `"vinyl-buffer": "^1.0.0",` in my package.json should fulfill the requirement of upgrading `vinyl-buffer` to 1.0.1.

**Comment by phated** [comment]
Very incorrect. Npm has become terrible and locks your stuff now

**Comment by fishcharlie** [comment]
@phated Thanks so much. Looks to be working now. Crazy that NPM changed it like that. Based on what I have read `"vinyl-buffer": "^1.0.0"` should TOTALLY work. Not sure why NPM changed that.

**Comment by phated** [comment]
@fishcharlie yep, it's a terrible system.  You can disable the package-lock feature in you config (I did).
