### ISSUE TITLE
"vinyl-source-stream" npm i returns error when

### ISSUE THREAD

**Issue by ghost** [hughsk/vinyl-source-stream#28]
...
1517 silly saveTree +-- react-dom@16.2.0
1517 silly saveTree +-- react@16.2.0
1517 silly saveTree +-- vinyl-buffer@1.0.1
1517 silly saveTree `-- vinyl-source-stream@2.0.0
1518 verbose type range
1519 verbose stack require-from-string: No matching version found for require-from-string@^1.1.0
...
npm ERR! code ETARGET
npm ERR! notarget No matching version found for require-from-string@^1.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'cosmiconfig'
npm ERR! notarget

**Comment by phated** [comment]
Hey @ArtemChornovol - this is actually a problem with your direct or a different indirect dependency.  We don't have `require-from-string` as one of our [dependencies](https://github.com/hughsk/vinyl-source-stream/blob/master/package.json#L7-L10).
  
Edit: Actually, the log says "It was specified as a dependency of 'cosmiconfig'" so I'm guessing it was `cosmiconfig`
